[package]
name = "mtpng"
version = "0.4.0"
authors = ["Brion Vibber <brion@pobox.com>"]
license = "MIT"
description = "Multithreaded PNG encoder library"
readme = "readme.md"
homepage = "https://github.com/brion/mtpng"
repository = "https://github.com/brion/mtpng.git"
keywords = ["png", "multithreaded", "threaded", "parallel"]
categories = ["multimedia::images"]

[features]
default=[]
cli=["png", "clap", "time"]
capi=["libc"]

[[bin]]
name="mtpng"
path="src/bin/mtpng.rs"
required-features=["cli"]

[dependencies]
rayon = "1.5.0"
crc = "1.8.1"
libz-sys = "1.0.23"
itertools = "0.10.0"

# for cli
png = { version = "0.16.8", optional = true }
clap = { version = "2.33.0", optional = true }
time = { version = "0.2.26", optional = true }

# for capi
libc = { version = "0.2.43", optional = true }

[lib]
crate-type = ["rlib", "cdylib", "staticlib"]

[profile.release]
## Unoptimized debug builds are too slow to profile!
## Having debug info doesn't hurt perf but does increase
## size, so enable this if needed.
# debug = true
