[package]
name = "mtpng"
version = "0.3.4"
authors = ["Brion Vibber <brion@pobox.com>"]
license = "MIT"
description = "Multithreaded PNG encoder library"
readme = "readme.md"
homepage = "https://github.com/brion/mtpng"
repository = "https://github.com/brion/mtpng.git"
keywords = ["png", "multithreaded", "threaded", "parallel"]
categories = ["multimedia::images"]
edition = "2018"
include = [
  "license.md",
  "readme.md",
  "src/",
]

[features]
default=[]
cli=["png", "clap"]
capi=["libc"]

[[bin]]
name="mtpng"
path="src/bin/mtpng.rs"
required-features=["cli"]

[dependencies]
rayon = "1.5"
crc = "1.8.1"
libz-sys = "1.1"
itertools = "0.9"
typenum = "1.12"

# for cli
png = { version = "0.16", optional = true }
clap = { version = "2.33", optional = true }

# for capi
libc = { version = "0.2", optional = true }

[lib]
crate-type = ["rlib", "cdylib", "staticlib"]

[profile.release]
## Unoptimized debug builds are too slow to profile!
## Having debug info doesn't hurt perf but does increase
## size, so enable this if needed.
# debug = true
