[package]
name = "mtpng"
version = "0.4.0"
authors = ["Brion Vibber <brion@pobox.com>", "Daniel Santana <danielgsantana@gmail.com>"]
license = "MIT"
description = "Multithreaded PNG encoder library"
readme = "readme.md"
homepage = "https://github.com/brion/mtpng"
repository = "https://github.com/brion/mtpng.git"
keywords = ["png", "multithreaded", "threaded", "parallel"]
categories = ["multimedia::images"]
edition = "2021"

[features]
default=["miniz"]
cli=["png", "clap", "time"]
capi=["libc"]
zlib = ["libz-sys"]
miniz = ["miniz_oxide", "simd-adler32"]

[[bin]]
name="mtpng"
path="src/bin/mtpng.rs"
required-features=["cli"]

[dependencies]
rayon = "1.5"
crc = "2.1"
libz-sys = { version = "1.1.3", optional = true}
itertools = "0.10"
miniz_oxide = { version = "0.4", optional = true }
simd-adler32 = { version = "0.3", optional = true }
typenum = "1.14"

# for cli
png = { version = "0.16", optional = true }
clap = { version = "2.33", optional = true }
time = { version = "0.3", optional = true }

# for capi
libc = { version = "0.2", optional = true }

[lib]
crate-type = ["rlib", "cdylib", "staticlib"]

[profile.release]
## Unoptimized debug builds are too slow to profile!
## Having debug info doesn't hurt perf but does increase
## size, so enable this if needed.
# debug = true
